import { artImage } from "@/lib/mock-images";
import { ETH_PRICE_USD } from "@/lib/mock-tokens";
import type { NftCollection, NftItem } from "@/types/nft";

type MockNftInput = Omit<NftItem, "id" | "imageUrl" | "openseaUrl"> & {
  colors: readonly [string, string];
};

const createNft = ({ colors, ...nft }: MockNftInput): NftItem => ({
  ...nft,
  id: `${nft.contractAddress}:${nft.tokenId}`,
  imageUrl: artImage(nft.name, colors),
  openseaUrl: `https://opensea.io/assets/ethereum/${nft.contractAddress}/${nft.tokenId}`,
});

export const BASE_NFT_COLLECTIONS: NftCollection[] = [
  {
    contractAddress: "0xb47e3cd837dDF8e4c57F05d70Ab865de6e193BBB",
    name: "CryptoPunks",
    slug: "cryptopunks",
    description: "Pixel portraits from one of Ethereum's earliest NFT collections.",
    imageUrl: artImage("Punks", ["#111827", "#eab308"]),
    floorPriceEth: 37.2,
    floorPriceUsd: 37.2 * ETH_PRICE_USD,
    itemCount: 10000,
    ownedCount: 2,
    nfts: [
      createNft({
        contractAddress: "0xb47e3cd837dDF8e4c57F05d70Ab865de6e193BBB",
        tokenId: "6529",
        name: "CryptoPunk #6529",
        description: "A rare statement piece for the gallery entrance wall.",
        collectionName: "CryptoPunks",
        collectionSlug: "cryptopunks",
        floorPriceEth: 37.2,
        estimatedValueUsd: 168000,
        rarityRank: 411,
        rarityScore: 82.4,
        isRare: true,
        traits: [{ traitType: "Type", value: "Human", rarityPercent: 60.39 }],
        colors: ["#111827", "#facc15"],
      }),
      createNft({
        contractAddress: "0xb47e3cd837dDF8e4c57F05d70Ab865de6e193BBB",
        tokenId: "7804",
        name: "CryptoPunk #7804",
        description: "A blue-chip portrait shown as a large-format frame.",
        collectionName: "CryptoPunks",
        collectionSlug: "cryptopunks",
        floorPriceEth: 37.2,
        estimatedValueUsd: 152000,
        rarityRank: 628,
        rarityScore: 77.1,
        isRare: true,
        traits: [{ traitType: "Accessory", value: "Shades", rarityPercent: 5.2 }],
        colors: ["#0f172a", "#22d3ee"],
      }),
    ],
  },
  {
    contractAddress: "0xa7d8d9ef8D8Ce8992Df33D8b8CF4Aebabd5bD270",
    name: "Art Blocks",
    slug: "art-blocks",
    description: "Generative artworks arranged across the main gallery wall.",
    imageUrl: artImage("Blocks", ["#f43f5e", "#14b8a6"]),
    floorPriceEth: 1.8,
    floorPriceUsd: 1.8 * ETH_PRICE_USD,
    itemCount: 32000,
    ownedCount: 2,
    nfts: [
      createNft({
        contractAddress: "0xa7d8d9ef8D8Ce8992Df33D8b8CF4Aebabd5bD270",
        tokenId: "13000821",
        name: "Chromie Study #821",
        description: "A bright generative composition for the central wing.",
        collectionName: "Art Blocks",
        collectionSlug: "art-blocks",
        floorPriceEth: 1.8,
        estimatedValueUsd: 9800,
        rarityRank: 1204,
        rarityScore: 46.8,
        isRare: false,
        traits: [{ traitType: "Palette", value: "Electric" }],
        colors: ["#f97316", "#10b981"],
      }),
      createNft({
        contractAddress: "0xa7d8d9ef8D8Ce8992Df33D8b8CF4Aebabd5bD270",
        tokenId: "78000112",
        name: "Fidenza Echo #112",
        description: "A calm geometric work suited for a quiet side wall.",
        collectionName: "Art Blocks",
        collectionSlug: "art-blocks",
        floorPriceEth: 1.8,
        estimatedValueUsd: 12400,
        rarityRank: 932,
        rarityScore: 51.9,
        isRare: false,
        traits: [{ traitType: "Flow", value: "Curved" }],
        colors: ["#0ea5e9", "#a855f7"],
      }),
    ],
  },
  {
    contractAddress: "0xED5AF388653567Af2F388E6224dC7C4b3241C544",
    name: "Azuki",
    slug: "azuki",
    description: "Character art grouped as a smaller collection room.",
    imageUrl: artImage("Azuki", ["#dc2626", "#111827"]),
    floorPriceEth: 4.6,
    floorPriceUsd: 4.6 * ETH_PRICE_USD,
    itemCount: 10000,
    ownedCount: 1,
    nfts: [
      createNft({
        contractAddress: "0xED5AF388653567Af2F388E6224dC7C4b3241C544",
        tokenId: "4096",
        name: "Azuki #4096",
        description: "A character artwork reserved for a spotlight frame.",
        collectionName: "Azuki",
        collectionSlug: "azuki",
        floorPriceEth: 4.6,
        estimatedValueUsd: 18100,
        rarityRank: 740,
        rarityScore: 59.6,
        isRare: false,
        traits: [{ traitType: "Background", value: "Off White" }],
        colors: ["#dc2626", "#f59e0b"],
      }),
    ],
  },
];
